spin_manifest_version = 2

[application]
name = "hello-webserver"
version = "0.1.0"
authors = ["M.-Leander Reimer <mario-leander.reimer@qaware.de>"]
description = "Webserver to serve some static files"

[[trigger.http]]
route = "/static/..."
component = "hello-webserver"

[component.hello-webserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
