apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-cdi
provisioner: pd.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard