apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml
 - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.crds.yaml
 - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.runtime-class.yaml
 - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.shim-executor.yaml
