spin_manifest_version = 2

[application]
name = "hello-spinkube"
version = "0.1.0"
authors = ["M.-Leander Reimer <mario-leander.reimer@qaware.de>"]
description = "HTTP request handler demo using Rust running on Spinkube"

[[trigger.http]]
route = "/spinkube"
component = "hello-spinkube"

[component.hello-spinkube]
source = "target/wasm32-wasip1/release/hello_spinkube.wasm"
allowed_outbound_hosts = []
[component.hello-spinkube.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
